## makefile for the compiler-optimization homework

P1:
	cc P10-1.c -o P10-1
	./P10-1 line_set1.txt
	./P10-1 line_set1.txt -sort

P1-O1:
	cc -O1 P10-1.c -o P10-1-O1
	./P10-1-O1 line_set1.txt
	./P10-1-O1 line_set1.txt -sort

P1-O2:
	cc -O2 P10-1.c -o P10-1-O2
	./P10-1-O2 line_set1.txt
	./P10-1-O2 line_set1.txt -sort

P1-O3:
	cc -O3 P10-1.c -o P10-1-O3
	./P10-1-O3 line_set1.txt
	./P10-1-O3 line_set1.txt -sort

P2:
	cc P10-2.c -o P10-2
	./P10-2 line_set1.txt	

P2-O1:
	cc -O1 P10-2.c -o P10-2-O1
	./P10-2-O1 line_set1.txt

P2-O2:
	cc -O2 P10-2.c -o P10-2-O2
	./P10-2-O2 line_set1.txt

P2-O3:
	cc -O3 P10-2.c -o P10-2-O3
	./P10-2-O3 line_set1.txt


##### 